#!/bin/bash

# External variables
PROJECT_PATH="${1}"
ARCH="${2}"
COMMAND=${3}

if [ "${ARCH}" == "" ]; then
  ARCH="${HEMERA_BUILD_ARCH}"
fi
if [ "${ARCH}" == "" ]; then
  ARCH="i586"
fi

# Common variables
SHARED_SOURCE_BASE="/usr/share/hemera-devel-tools"
SHARED_SOURCE_PATHS="${SHARED_SOURCE_BASE}/hemera-vars-paths"
SHARED_SOURCE_SB2="${SHARED_SOURCE_BASE}/hemera-vars-sb2"

if ! [ -f "${SHARED_SOURCE_PATHS}" ]; then
  echo "Missing \"${SHARED_SOURCE_PATHS}\" source file. Cannot continue."
  exit 1
fi
source "${SHARED_SOURCE_PATHS}"

if [ "${ARCH}" != "i586" ]; then
  if ! [ -f "${SHARED_SOURCE_SB2}" ]; then
    echo "Missing \"${SHARED_SOURCE_SB2}\" source file. Cannot continue."
    exit 1
  fi
  source "${SHARED_SOURCE_SB2}"
fi

# Other variables
if [ "${ARCH}" == "i586" ]; then
  FULL_BUILD_PATH="${BUILD_PATH}"
  # if there is no build project path probably we don't care
  # we can just move to /build and live happy there
  if [ ! -d "${FULL_BUILD_PATH}" ]; then
      FULL_BUILD_PATH="${BUILD_BASE_PATH}"
  fi
  EXECUTOR=""
else
  FULL_BUILD_PATH="${TARGET_PATH}${BUILD_PATH}"
  # if there is no build project path probably we don't care
  # we can just move to /build and live happy there
  if [ ! -d "${FULL_BUILD_PATH}" ]; then
      FULL_BUILD_PATH="${TARGET_PATH}${BUILD_BASE_PATH}"
  fi
  EXECUTOR="${SB2TMR}"
fi

if [ ! -d "${FULL_BUILD_PATH}" ]; then
  mkdir -p ${FULL_BUILD_PATH}
fi

ARGS=( "$@" )
COMMAND_ARGS=""
I=3
while [ $I -lt $# ]; do
  if [ $I -eq 3 ]; then
    COMMAND_ARGS="${ARGS[$I]}"
  else
    COMMAND_ARGS="${COMMAND_ARGS} ${ARGS[$I]}"
  fi
  let I=I+1
done

# Let's do the work
cd ${FULL_BUILD_PATH} &&
${EXECUTOR} ${COMMAND} ${COMMAND_ARGS}
exit $?
